
import Head from "next/head";
import Link from "next/link";
import AuthenticationButton from "~/components/AuthenticationButton";
import CreateArea from "~/components/CreateArea";
import Footer from "~/components/Footer";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center" style={{ backgroundImage: "url('https://www.transparenttextures.com/patterns/carbon-fibre-big.png')", backgroundColor: " #0061b5" }}>
   
          <div className="flex flex-col items-center gap-2">
            <AuthenticationButton />
          </div>
          <CreateArea />
          <Footer />
      </main>
    </>
  );
}
